version: '2'
services:
  database:
    image: mongo:3.4
    ports:
      - "27027:27017"
    volumes:
      - ../backup:/backup

  rest:
    depends_on:
      - database
    image: inovatrend/tomcat8-java8
    ports:
      - "8088:8080"
    volumes:
      - ../databucket/build/libs/rest-0.1.0.war:/opt/tomcat/webapps/rest-0.1.0.war
