version: '2'
services:
  database:
    image: mongo:3.4
    ports:
      - "27027:27017"
    volumes:
      - ../backup:/backup

  rest:
    depends_on:
      - database
    image: inovatrend/tomcat8-java8
    ports:
      - "8088:8080"
      - "8098:8090"
    environment:
      - DB_HOST=database
      - DB_PORT=27017
    volumes:
      - ../databucket/build/libs/rest-0.1.0.war:/opt/tomcat/webapps/rest-0.1.0.war
      - ./logs/rest:/opt/tomcat/logs

  web:
    image: inovatrend/tomcat8-java8
    ports:
      - "8089:8080"
    volumes:
      - ../databucket/build/libs/databucker-website.war:/opt/tomcat/webapps/databucker-website.war
      - ./logs/web:/opt/tomcat/logs